[general]
import = [
  "./themes/tokyonight-moon.toml",
  "./themes/kanagawa-paper-ink.toml"
]

[window]
dimensions = { lines = 25 , columns = 125 }
padding= { x = 0, y = 0 }
opacity = 0.95

[font] 
normal = {family = "SpaceMono Nerd Font", style = "normal" }
bold = {family = "SpaceMono Nerd Font", style = "bold" }
italic = {family = "SpaceMono Nerd Font", style = "italic" }
bold_italic = {family = "SpaceMono NerdFont", style = "bold italic" }
size = 11
offset= { x = 0, y = 2 }

[cursor]
style = { shape = "Underline", blinking = "Always" }

[mouse]
hide_when_typing = true

