[general]
import = [
  "./themes/tokyonight-moon.toml",
  "./themes/kanagawa-paper-ink.toml"
]

[window]
# dimensions = { lines = 35 , columns = 150 }
decorations = "Full"
padding = { x = 0, y = 0 }
opacity = 0.95

[font] 
normal = {family = "GohuFont 11 Nerd Font Mono", style = "normal" }
bold = {family = "GohuFont 11 Nerd Font Mono", style = "bold" }
italic = {family = "GohuFont 11 Nerd Font Mono", style = "italic" }
bold_italic = {family = "GohuFont 11 Nerd Font Mono", style = "bold italic" }
size = 12
offset= { x = 0, y = 2 }

[cursor]
style = { shape = "Underline", blinking = "Always" }

[mouse]
hide_when_typing = true

